Image modifier changes
ONSdigital/sdx-transform-cora pull request #22
Opened 2017-05-09 14:19 UTC by shahi645

- Reformat image to make answers more prominent

2017-05-09 20:57 UTC, JamesGardiner requested changes

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
> +from copy import copy
Try and keep imports alphabetised

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
> +styleN = copy(styles["BodyText"])
Are you aware that this is only returning a shallow copy of `styles["BodyText"]` the difference being:


    - A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.
    - A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.

You might want to consider which to use here (though that's not to say this is the wrong choice!)

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
> +styleAnswer = copy(styles["BodyText"])
can we change var names to be PEP8 compliant https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables `lowercase with words separated by underscores as necessary to improve readability`

2017-05-09 20:57 UTC, JamesGardiner commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This shouldn't have been commited. Remove this from the git repo, and add .idea to your global .gitignore

2017-05-09 20:57 UTC, JamesGardiner commented on tests/test_cora_transform.py
> +            ("3.3", "3.5", "3.8", "3.10", "3.12", "3.14", "3.17", "11.1"),
Why is 11.1 now in the first tuple?

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
>                  for question in question_group['questions']:
Could be rewritten something like this:

```python
for question_group in filter(lambda x: 'title' in x, self.survey['question_groups']):

            has_section_heading_output = False

            for question in filter(lambda x: 'text' in x, question_group['questions']):
```

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
>          for question_group in self.survey['question_groups']:
Could be rewritten something like this:

```python
for question_group in filter(lambda x: 'title' in x, self.survey['question_groups']):
    has_section_heading_output = False
    for question in filter(lambda x: 'text' in x, question_group['questions']):
```

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
>                          if question['question_id'] in self.response['data']:
This  would be an ideal try/except block

```python
try:
    answer = self.response['data'][question['question_id']]
except KeyError:
    answer = ''
```

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
> +                            text = question.get("text", " ")
didn't you check above that text is present in question?

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
>      with open(fP, "r") as fObj:
pep8 variable name again

2017-05-09 20:57 UTC, JamesGardiner commented on transform/transformers/PDFTransformer.py
> +        sys.stdout.write(output.decode("latin-1"))
Is latin-1 a requirement of the downstream??

2017-05-10 10:17 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
> +from copy import copy
done

2017-05-10 10:36 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
> +styleN = copy(styles["BodyText"])
done

2017-05-10 10:36 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
> +styleAnswer = copy(styles["BodyText"])
done

2017-05-10 10:36 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
>          for question_group in self.survey['question_groups']:
done

2017-05-10 10:39 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
>                  for question in question_group['questions']:
done

2017-05-10 10:39 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
>                          if question['question_id'] in self.response['data']:
done

2017-05-10 10:40 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
> +                            text = question.get("text", " ")
done

2017-05-10 10:40 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
>      with open(fP, "r") as fObj:
done

2017-05-10 10:40 UTC, shahi645 commented on transform/transformers/PDFTransformer.py
> +        sys.stdout.write(output.decode("latin-1"))
changed to utf-8

2017-05-11 13:25 UTC, JamesGardiner approved these changes

2017-05-11 13:52 UTC, tundish requested changes

2017-05-11 13:52 UTC, tundish commented on transform/transformers/PDFTransformer.py
> +        sys.stdout.write(output.decode("utf-8"))
_latin-1_  was the necessary encoding.

2017-05-11 13:55 UTC, tundish approved these changes

2017-05-12 07:37 UTC, merged