Delete tmp files even when failure
ONSdigital/sdx-transform-cora pull request #40
Opened 2017-09-19 09:03 UTC by dcdarrell9

## What? and Why?
> Makes sure that all tmp files get deleted to stop disk space being full.

## Checklist
  - [ ] CHANGELOG.md updated? (if required)

2017-09-19 09:26 UTC, dcdarrell9 commented
![](https://github.trello.services/images/mini-trello-icon.png) [sdx-transform-cs/cora tmp files do not get deleted when the transform fails](https://trello.com/c/01sVkI1I/401-sdx-transform-cs-tmp-files-do-not-get-deleted-when-the-transform-fails)

2017-09-21 10:19 UTC, JamesGardiner requested changes

2017-09-21 10:19 UTC, JamesGardiner commented on tests/test_transform.py
> +from transform.transformers.ImageTransformer import ImageTransformer
Import statements need to be pep8 compliant

2017-09-21 10:53 UTC, JamesGardiner requested changes

2017-09-21 10:53 UTC, JamesGardiner commented on tests/test_transform.py
>  from datetime import datetime
Nearly there, just get these last two alphabetised and that's good to go.

2017-09-22 08:15 UTC, JamesGardiner approved these changes

2017-09-22 08:16 UTC, merged