Initial files for move to cloudfoundry
ONSdigital/sdx-transform-cora pull request #53
Opened 2017-11-15 11:07 UTC by AndrewTorrance

## What? and Why?
> Initial files for move to cloudfoundry 

## Checklist
  -  CHANGELOG.md updated?

2017-11-15 11:08 UTC, AndrewTorrance commented
![](https://github.trello.services/images/mini-trello-icon.png) [2nd 1/2 SDX into Cloudfoundry (5)](https://trello.com/c/bB87Q2Se/522-2nd-1-2-sdx-into-cloudfoundry-5)

2017-11-15 15:36 UTC, warrenbailey requested changes

2017-11-15 15:36 UTC, warrenbailey commented on manifest.yml
> +    FTP_PATH: \\\\NP3RVWAPXX370\\SDX_preprod\\
Since it's not preprod, I don't think we need this path. It probably can just be "\"

2017-11-15 15:36 UTC, warrenbailey commented on transform/settings.py
> +if not os.getenv("CF_DEPLOYMENT", False):
You'll still need these set regardless

2017-11-15 15:36 UTC, warrenbailey commented on transform/settings.py
> -SDX_SEQUENCE_URL = os.getenv("SDX_SEQUENCE_URL", "http://sdx-sequence:5000")
And I think you need this default value for when it runs in compose

2017-11-16 15:07 UTC, AndrewTorrance commented on transform/settings.py
> -SDX_SEQUENCE_URL = os.getenv("SDX_SEQUENCE_URL", "http://sdx-sequence:5000")
Done

2017-11-17 07:53 UTC, warrenbailey approved these changes

2017-11-17 07:55 UTC, merged